### Create user
POST {{registrationUrl}}/registration
Content-Type: application/json

{"name": "Pete"}

### Get user
GET {{registrationUrl}}/users/2
Authorization: Bearer {{token}}

### Get account
GET {{registrationUrl}}/accounts?ownerId=2
Authorization: Bearer {{token}}

### Create project
POST {{registrationUrl}}/projects
Content-Type: application/json

{"name": "Basket Weaving B", "accountId": 2}

### Get projects
GET {{registrationUrl}}/projects?accountId=2
Authorization: Bearer {{token}}

### Create allocation
POST {{allocationsUrl}}/allocations
Authorization: Bearer {{token}}
Content-Type: application/json

{"projectId": 2, "userId": 2, "firstDay": "2015-05-17", "lastDay": "2015-05-18"}

### Get allocations
GET {{allocationsUrl}}/allocations?projectId=2
Authorization: Bearer {{token}}

### Create story
POST {{backlogUrl}}/stories
Authorization: Bearer {{token}}
Content-Type: application/json

{"projectId": 2, "name": "Find some reeds"}

### Get stories
GET {{backlogUrl}}/stories?projectId=4

### Create timesheet
POST {{timesheetsUrl}}/time-entries/
Authorization: Bearer {{token}}
Content-Type: application/json

{"projectId": 2, "userId": 2, "date": "2015-05-17", "hours": 6}

### Get timesheets
GET {{timesheetsUrl}}/time-entries?userId=2
Authorization: Bearer {{token}}

###
